Improve get_power and get_ohmic_parameters
MIT-PSFC/disruption-py pull request #367
Opened 2024-12-23 19:50 UTC by yumouwei

# Original problems

1. `p_lh` and `p_rad` data stored in the MDSplus trees have shorter time bases than EFIT for a few shots (e.g. 1120208014 and 1050725002). This causes disruption-py to return nans for these signals (plus `p_input` and `radiated_fraction` which use these signals in their computation) in the missing time period, subsequently causing the ONW module to give bad predictions during these periods.
2. `get_ohmic_parameters` method fails for a few shots (e.g. 1050608005), which also causes `get_power` to fail.

![image](https://github.com/user-attachments/assets/68fdbd71-10f0-4a60-b4bf-2e765236d2d5)
![image](https://github.com/user-attachments/assets/c56d8fff-a1cc-4b2f-9466-65cc05f05ff9)

# Implemented changes

1. Added `interp1(..., fill_value=0)` for `p_lh`, `p_icrh`, and `p_rad` in `_get_power`. It should be safe to assume that these auxiliary heatings were turned off during the periods where there were no data stored in the tree.
2. Added a try-except block in `get_ohmic_parameters` to return `nans` for `v_loop` and `p_ohm`. 
3. *Modified `_get_power` so that the `p_input` and `radiated_fraction` computations will take `p_ohm=0` even if `get_ohmic_parameters` fails.
    - `p_ohm` and `v_loop` should not be 0 even if there's no data stored in that node in a shot. I want to see there's a better way to do this (see TODO below)
    - This does not affect disruption-py's outputs for these two signals. They will still be arrays of nans when `get_ohmic_parameters` fails.

(Before -- dev)
![image](https://github.com/user-attachments/assets/f74a2ee7-d7d3-4090-979b-c33cc573b72d)

(After)
![image](https://github.com/user-attachments/assets/ec58147b-cf99-4761-8fa3-11e2cfb967c3)

# TODO

- [ ] Should we switch to using `\efit_aeqdsk:vloopt` (i.e. `v_loop_efit`), or to use it as a backup in case there's no data stored in `mflux:v0`? @crea-psfc 
- [ ] @amdecker Can you take a look at the try-except block to make sure I didn't make any mistake?
- [ ] @AlexSaperstein Can you add `tau_rad` and `tau_rad_normalized` from your ONW modules to the `get_power` method?

2025-01-02 16:19 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
is this needed?
didn't the previous version of the code return NaNs, as well, if TreeNODATA was triggered?

I might be wrong, of course. :)

2025-01-02 16:19 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        if len(p_ohm) == 1 and np.isnan(p_ohm[0]):
`if all(np.isnan(p_ohm))`?

2025-01-02 16:52 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
it should be caught here, and should effectively return a full-NaN array:
https://github.com/MIT-PSFC/disruption-py/blob/35b3f99b77552413216bdb762237c021350f18a0/disruption_py/core/physics_method/runner.py#L219-L228

2025-01-06 16:28 UTC, yumouwei commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
So the problem is `get_power` calls `get_ohmic_parameters`; if `get_power` fails then it causes `get_ohmic_parameters` to fail and return nans for its outputs even if there are data for those signals in the tree.

https://github.com/MIT-PSFC/disruption-py/blob/efc63b986e36ef2e555b2f3df632ffe80a67fe66/disruption_py/machine/cmod/physics.py#L630-L641

I forgot why I put that try-except block in `get_power`. I guess the better way is to put it around line 639.

2025-01-06 16:30 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
who calls who? maybe you mistyped -- it's the caller that should catch the mdsplus exception, then.

2025-01-06 16:32 UTC, yumouwei commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
Yeah there was a mistake. `get_power` calls `get_ohmic_parameters` and `_get_power`

2025-01-06 16:35 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
yep, okay, so then your try/except definitely needs to wrap line 639. :+1:

2025-01-06 16:36 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeNODATA:
(also, removing such indentation might suppress the current conflict with `dev`.)

2025-01-06 16:51 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        if all(np.isnan(p_ohm)):
further thought -- do we want to set values to zero only for a full-NaN array?
could we have some values and some NaNs, instead?
another way, maybe more functional, is using `np.nan_to_num` which replaces NaN with 0 by default, wherever they might appear.

2025-01-06 16:56 UTC, yumouwei commented on disruption_py/machine/cmod/physics.py
> +        if all(np.isnan(p_ohm)):
Actually that's a good idea, although I haven't found a shot where vloop has a shorter time base than efit so we won't be able to test this.

2025-01-07 16:26 UTC, gtrevisan commented
@yumouwei please double check my kwarg commit! also, was there an error about `p_oh` vs `p_ohm`?
is `_get_ohmic_parameters` supposed to return `p_oh` without a trailing M?

2025-01-07 16:44 UTC, yumouwei commented
Yes that's one of the annoying things with the CMOD branch. The Ohmic power is referred to as `p_ohm` everywhere else except in the column name which is called `p_oh`. This whole mess is needed to be consistent with the SQL table. To make it even worse, the DIII-D table has `p_ohm` while the EAST table has `p_oh` as their respective column name.

2025-01-08 16:45 UTC, yumouwei commented
`get_ohmic_parameters` will now use `\efit_aeqdsk:vloopt` when `\top:mflux:v0` data isn't available. This significantly changes the values of `p_input` and `radiated_fraction`.

(post change)
![image](https://github.com/user-attachments/assets/75653453-fd88-4457-ac41-9fdb2c962427)

2025-01-08 17:01 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +            kwa["p_ohm"] = CmodPhysicsMethods.get_ohmic_parameters(params=params)[
well at this point you can break it up with `output =` or `result =` and then assign it into `kwa` on the following line.

2025-01-08 18:06 UTC, gtrevisan requested changes

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeException:
maybe we should add a debug* statement here to track this fallback.
*: it will be a verbose statement once we merge that PR.

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +            The EFIT time base
missing final full stop for consistency.

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        Last major update by William Wei on 1/6/2025
I am now unsure whether to keep adding changelog lines like this one in the docstrings, since we (mostly you) touched up most of the physics parameters anyways... I welcome suggestions on this.

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        p_ohm = np.nan_to_num(p_ohm, nan=0.0)
have you tried replacing it in-place, as well?
```python
np.nan_to_num(p_ohm, copy=False, nan=0.0)
```

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> -        for i in range(3):
would you be able to take care of the TODO here above? since we are at it? thanks!

2025-01-08 18:06 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +                kwa[p], kwa[t] = params.mds_conn.get_data_with_dims(
does this make sense to you? it's better than the `*values` trick but I'm not happy with how this turned out following my commit. any improvement is welcome.

2025-01-09 09:21 UTC, amdecker commented on disruption_py/machine/cmod/physics.py
> +        tau_rad[tau_rad == np.inf] = np.nan
Minor: instead of 
```python
with np.errstate(divide="ignore", invalid="ignore"):
    tau_rad = wmhd / p_rad
tau_rad[tau_rad == np.inf] = np.nan
```
we can do
```python
tau_rad = np.full_like(wmhd, np.nan)
np.divide(wmhd, p_rad, out=tau_rad, where=p_rad != 0)
```
to more explicitly handle divisions by zero. This ensures we only perform the division where `p_rad` is non-zero and anywhere we would have divided by is a nan instead of inf. I like this better than ignoring the errors because it is more explicit, but lmk if you prefer the `with` statement

2025-01-09 14:15 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        tau_rad[tau_rad == np.inf] = np.nan
no offense, but that's ugly! :chipmunk: 
what about something more physics-based, but still explicit, like so?
```python
tau_rad = wmhd / np.where(p_rad != 0, p_rad, np.nan)
```
that should be sufficient by itself. LMK!

2025-01-09 14:47 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +                kwa[p], kwa[t] = params.mds_conn.get_data_with_dims(
@amdecker thoughts on making this prettier yet robust and explicit?

2025-01-09 16:19 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        except mdsExceptions.TreeException:
you can now use the verbose level!

2025-01-09 16:24 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        Last major update by William Wei on 1/6/2025
I thought about it -- we should put here only actionable intel, that is, references to PRs that modified the physics or logic.
in such a way we can quickly backtrack through physics changes without being submerged by github blame info that would also include lots of refactoring/linting/logging-based PRs.
so something like:
```python
"""
References
----------
- https://github.com/MIT-PSFC/disruption-py/pull/367
"""
```

or any other format appropriate for reading _and_ for mkdocs-generated documentation.
@amdecker?

2025-01-09 19:29 UTC, yumouwei commented on disruption_py/machine/cmod/physics.py
> +        Last major update by William Wei on 1/6/2025
Added References block in docstring.

2025-01-09 19:40 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +                    node, tree_name=tree
bug I introduced inadvertently in:
https://github.com/MIT-PSFC/disruption-py/pull/364/files#diff-13362dcb51f88ed4cb8a9a082dca2ce1997dc3e8c9e3c2635e9e565b64438120

2025-01-09 19:43 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        Last major update by William Wei on 1/6/2025
thanks, we will have to remove all lines like "Last major update" by replacing them with PR links, but it can be a separate PR.

2025-01-09 19:46 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        - Radiated: \spectroscopy::top.bolometer.twopi_diode [kW]
what error did you get? it worked on my end without this change. what version of pylint?

2025-01-09 19:48 UTC, yumouwei commented on disruption_py/machine/cmod/physics.py
> +        - Radiated: \spectroscopy::top.bolometer.twopi_diode [kW]
I added the `r"""` before the docstring which you introduced in your commit as well.

2025-01-09 20:01 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        - Radiated: \spectroscopy::top.bolometer.twopi_diode [kW]
you reverted the wrong commit! lol.

2025-01-09 20:05 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +        Last major update by William Wei on 1/6/2025
you also added it to the wrong method (private vs public) but that's okay for now!
I opened up another issue in order to track this.

2025-01-09 20:07 UTC, gtrevisan commented on disruption_py/machine/cmod/physics.py
> +            params.logger.warning(
should we consider this a warning or just a fallback, thus using verbose?

2025-01-09 20:12 UTC, gtrevisan approved these changes
LGTM, please have Alex test this out, then I'll merge!

2025-01-13 14:25 UTC, AlexSaperstein approved these changes
Looks good to me. I compared tau_rad for shot 1120501008 between my onw_dev code calc and this update and they agree.

2025-01-15 14:05 UTC, merged